Import('env')
daemon_files = Split(
        """BnIotDaemon.cpp
	       BpIotDaemon.cpp
           IotDaemonProxy.cpp
           iotdaemon.cpp"""
        )


clientlib_files = Split(
        """BpIotDaemon.cpp
           """
        )

daemon_cflags = Split(
        """-DHAVE_PTHREADS
           -DHAVE_SYS_UIO_H
           -DHAVE_ENDIAN_H
           -DHAVE_ANDROID_OS=1"""
        )

clientlib_cflags = Split(
        """-DHAVE_PTHREADS
           -DHAVE_SYS_UIO_H
           -DHAVE_ENDIAN_H
           -DHAVE_ANDROID_OS=1"""
        )

env.Append(CPPPATH=['.', '../core/include/'])
env.Program('../bin/iotdaemon', daemon_files,  CCFLAGS=daemon_cflags, CXXFLAGS='-std=c++11', LIBS=['utils', 'binder', 'pthread', 'cutils'], LIBPATH='../libs/')
env.SharedLibrary('../libs/iotdaemon', clientlib_files,  CCFLAGS=clientlib_cflags, CXXFLAGS='-std=c++11', LIBS=['utils', 'binder', 'pthread', 'cutils'], LIBPATH='../libs/')
