Import('env')
utils_files = Split(
        """BasicHashtable.cpp
	       BlobCache.cpp
	       CallStack.cpp
	       FileMap.cpp
	       JenkinsHash.cpp
	       LinearTransform.cpp
	       Log.cpp
	       Looper.cpp
	       misc.cpp
	       NativeHandle.cpp
	       Printer.cpp
	       ProcessCallStack.cpp
	       PropertyMap.cpp
	       RefBase.cpp
	       SharedBuffer.cpp
	       Static.cpp
	       StopWatch.cpp
	       String16.cpp
	       String8.cpp
	       SystemClock.cpp
	       Threads.cpp
	       Timers.cpp
	       Tokenizer.cpp
	       Unicode.cpp
	       VectorImpl.cpp"""
        )
utils_cflags = Split(
        """-DHAVE_PTHREADS
           -DHAVE_SYS_UIO_H
           -DHAVE_ENDIAN_H
           -DHAVE_ANDROID_OS=1"""
        )
# toolkit.h is located in this directory, add it to the include path
env.Append(CPPPATH=['.', '../include/'])
# Let's declare a library named toolkit, using toolkit.c as its only source
env.SharedLibrary('../libs/utils', utils_files,  CCFLAGS=utils_cflags, CXXFLAGS='-std=c++11')
